### ISSUE TITLE
Valid Anagram question problem 

### ISSUE THREAD

**Issue by SarthakShindeOP** [devs-nest/devsnest-teams-backend#1]
it has a wrong url in it thew url is https://leetcode.com/problems/valid-anagram) which is wrong the bracket takes to unkown url so we can change it to https://leetcode.com/problems/valid-anagram

**Comment by sanjay270899** [comment]
> it has a wrong url in it thew url is https://leetcode.com/problems/valid-anagram) which is wrong the bracket takes to unkown url so we can change it to https://leetcode.com/problems/valid-anagram

@SarthakShindeOP you are at wrong repo.
Head towards https://github.com/devs-nest/backend.

**Comment by SarthakShindeOP** [comment]
Sorry for that

**Comment by sanjay270899** [comment]
@SarthakShindeOP It's Ok.
